// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdawukqSfq9rgZD8vD3JqgSLHzasg70lg',
    appId: '1:962928421927:web:47a174aa22d4370b21f202',
    messagingSenderId: '962928421927',
    projectId: 'phar-test-2494a',
    authDomain: 'phar-test-2494a.firebaseapp.com',
    storageBucket: 'phar-test-2494a.appspot.com',
    measurementId: 'G-DDLY98BLK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvJ01vxGsVK4-ortc3E60vr7m6kWrWUFY',
    appId: '1:962928421927:android:4fd1d23f08989e9821f202',
    messagingSenderId: '962928421927',
    projectId: 'phar-test-2494a',
    storageBucket: 'phar-test-2494a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM7GnfoWcVCUnpY0JaUePwG2Eh3jeJZVU',
    appId: '1:962928421927:ios:a427355d52832bbe21f202',
    messagingSenderId: '962928421927',
    projectId: 'phar-test-2494a',
    storageBucket: 'phar-test-2494a.appspot.com',
    iosBundleId: 'com.example.phar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM7GnfoWcVCUnpY0JaUePwG2Eh3jeJZVU',
    appId: '1:962928421927:ios:a427355d52832bbe21f202',
    messagingSenderId: '962928421927',
    projectId: 'phar-test-2494a',
    storageBucket: 'phar-test-2494a.appspot.com',
    iosBundleId: 'com.example.phar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdawukqSfq9rgZD8vD3JqgSLHzasg70lg',
    appId: '1:962928421927:web:f08d7ce23849ca4521f202',
    messagingSenderId: '962928421927',
    projectId: 'phar-test-2494a',
    authDomain: 'phar-test-2494a.firebaseapp.com',
    storageBucket: 'phar-test-2494a.appspot.com',
    measurementId: 'G-GBL71DHYDT',
  );
}
